#config/choices.yml

concepto:
  - Capital
  - Mora

especialidad:
  - Anatomía y Patología Buco Maxilo Facial
  - Auditoría
  - Cirugía y Traumatología Bucomaxilofacial
  - Clínica Estomatológica
  - Diagnóstico por Imágenes Buco Maxilo Faciales
  - Endodoncia
  - Implantología
  - Odontología Legal
  - Odontopediatría
  - Organización y Administración de Sistemas de Salud
  - Ortodoncia y Ortopedia de los Maxilares
  - Periodoncia
  - Prótesis Dento Buco Maxilar
  - Salud Pública


universidad:
  - Colegio de Odontólogos Distrito VIII
  - Universidad Argentina John F. Kennedy
  - Universidad Catolica de La Plata
  - Universidad de Buenos Aires
  - Universidad del Salvador
  - Universidad Maimónides
  - Universidad Nacional de Cordoba
  - Universidad Nacional de La Plata
